# VacationPy

In [27]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

### Store Part I results into DataFrame

In [28]:
df = pd.read_csv("../output_data/cities.csv")
df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Mahébourg,40,MU,1593577629,93,-20.41,57.70,18.00,1.50
1,Nanortalik,84,GL,1593577605,87,60.14,-45.24,4.53,3.09
2,Pevek,100,RU,1593577831,85,69.70,170.31,3.52,4.21
3,Mandera,77,KE,1593577857,61,3.94,41.87,26.26,9.25
4,Atuona,2,PF,1593577645,74,-9.80,-139.03,26.40,9.76

### Humidity Heatmap

In [29]:
gmaps.configure(api_key="AIzaSyB5wQl4YnfCRPM_uBO4YEJ9fIr4cSnlo0E")
# Customize window.
figure_layout = {
    'width':"720px",
    "height": "480px",
    "border": "1px solid black",
    "padding": "1px",
    "margin": "0 auto 0 auto"
}
fig = gmaps.figure(layout = figure_layout)
# Store locations
locations = df[["Lat", "Lng"]]
# Store humidity values
humidity_df = df["Humidity"]
heat_layer = gmaps.heatmap_layer(locations=locations, weights=humidity_df, 
                                 dissipating=True, max_intensity=df["Humidity"].max(), point_radius=10)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(border='1px solid black', height='480px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria

In [41]:
ideal_df = df.loc[(df["Max Temp"] >= 20) & (df["Max Temp"] <= 26) & 
                  (df["Cloudiness"] <= 40) & (df["Humidity"] <= 40)].reset_index()

print(f" The total number of ideal cities is: {len(ideal_df)}")

ideal_df

 The total number of ideal cities is: 9

,index,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,59,Moses Lake,1,US,1593577881,30,47.13,-119.28,21.00,8.20
1,102,Makat,8,KZ,1593577898,32,47.65,53.35,22.82,6.36
2,124,Vostok,0,RU,1593577906,36,46.49,135.88,24.48,3.41
3,132,Jalu,0,LY,1593577831,36,29.03,21.55,24.68,2.67
4,137,Sakakah,0,SA,1593577625,39,29.97,40.21,26.00,4.60
5,200,Port Augusta,0,AU,1593577834,25,-32.50,137.77,23.00,11.30
6,351,Alice Springs,5,AU,1593577999,21,-23.70,133.88,26.00,3.60
7,398,Mildura,40,AU,1593578017,24,-34.20,142.15,21.11,6.70
8,439,Narrabri,0,AU,1593577759,40,-30.32,149.78,21.00,4.10

### Hotel Map

In [31]:
place_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
geo_url =  'https://maps.googleapis.com/maps/api/geocode/json'

In [32]:
hotel_name = []
hotel_city = []
hotel_country = []
hotel_lat = []
hotel_lng = []

for index, row in ideal_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    location = str(lat) + ", " + str(lng)
    params_place = {'key':"AIzaSyB5wQl4YnfCRPM_uBO4YEJ9fIr4cSnlo0E",
              'location':location,
              "radius":5000,
              "type":"hotel",
              "keyword":"hotel"
             }
    params_geo = {'key':"AIzaSyB5wQl4YnfCRPM_uBO4YEJ9fIr4cSnlo0E",'address':location}
    
    try:
        response_place = requests.get(place_url, params=params_place).json()
        hotel_lat.append(response_place["results"][0]["geometry"]["location"]["lat"])
        hotel_lng.append(response_place["results"][0]["geometry"]["location"]["lng"])
        hotel_name.append(response_place["results"][0]["name"])

    except:
        hotel_lat.append(np.nan)
        hotel_lng.append(np.nan)
        hotel_name.append(np.nan)
    try:
        response_geo = requests.get(geo_url, params=params_geo).json()
        hotel_city.append(response_geo["results"][0]["address_components"][4]["long_name"])
    except:
        hotel_city.append(np.nan)
    try:
        response_geo = requests.get(geo_url, params=params_geo).json()
        hotel_country.append(response_geo["results"][0]["address_components"][5]["long_name"])
    except:
        hotel_country.append(np.nan)

In [36]:
hotel_dir = {"Hotel Name":hotel_name, "Lat":hotel_lat, 
             "Lng": hotel_lng, "Country":hotel_country,
             "City":hotel_city
            }
hotel_df = pd.DataFrame(hotel_dir).dropna()

In [37]:
gmaps.configure(api_key="AIzaSyB5wQl4YnfCRPM_uBO4YEJ9fIr4cSnlo0E")
# Customize window.
figure_layout = {
    'width':"720px",
    "height": "480px",
    "border": "1px solid black",
    "padding": "1px",
    "margin": "0 auto 0 auto"
}
fig = gmaps.figure(layout = figure_layout)
# Store locations
locations = df[["Lat", "Lng"]]
# Store humidity values
humidity_df = df["Humidity"]
heat_layer = gmaps.heatmap_layer(locations=locations, weights=humidity_df, 
                                 dissipating=True, max_intensity=df["Humidity"].max(), point_radius=10)
fig.add_layer(heat_layer)
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

In [38]:
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='480px', margin='0 auto 0 auto', padding='1px', wi…